### ISSUE TITLE
Could not find a segue class named 'GuillotineMenuSegue

### ISSUE THREAD

**Issue by cjnwan** [Yalantis/GuillotineMenu#11]

**Comment by cjnwan** [comment]
barButton add segue

**Comment by Art3mS1d** [comment]
Can you provide more information? Maybe a screenshot with this error.

**Comment by Mourad-Khalfallaoui** [comment]
With copy/paste Activity viewController in the exemple project and setting a new segue on Settings button of the menu I have the same problem :
GuillotineMenuExample[3271:685038] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a segue class named 'GuillotineMenuSegue''
