### ISSUE TITLE
How to manage multiple view controller through navigation items?

### ISSUE THREAD

**Issue by willowcheng** [Yalantis/GuillotineMenu#8]
I'm not sure the general pattern for selecting different items in navigation and may need some guides for that. I'm really excited with this framework. 

By the way, how to change default background color for GuillotineMenuViewController?

**Comment by Art3mS1d** [comment]
Hi. To change background color of GuillotineMenuViewController you need to change color of navigationBar:

```
        let navBar = self.navigationController!.navigationBar
        navBar.barTintColor = UIColor(red: 65.0 / 255.0, green: 62.0 / 255.0, blue: 79.0 / 255.0, alpha: 1)
```

**Comment by Mourad-Khalfallaoui** [comment]
Hi,
your post title is "How to manage multiple view controller through navigation items?" but your question is about the menu background color. I try to integrate GuillotineMenu with différente viewController with keeping his beautiful animation, I have fallow readme instructions but it doesn't work, I have that error: 
GuillotineMenuExample[3239:679815] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a segue class named 'GuillotineMenuSegue'.

GuillotineMenuSegue is already included in the target of project

**Comment by mrcompoteee** [comment]
The new version of GuillotineMenu (2.0.1) is available. Feel free to check it out!
